/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Hijabpage extends javax.swing.JFrame {

    /**
     * Creates new form Hijabpage
     */
    public Hijabpage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("windows")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWellcome5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        bnlimage3 = new javax.swing.JPanel();
        lblimage4 = new javax.swing.JLabel();
        bnlimage4 = new javax.swing.JPanel();
        lblimage5 = new javax.swing.JLabel();
        lblimage6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblprice4 = new javax.swing.JLabel();
        lblprice5 = new javax.swing.JLabel();
        lblprice6 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWellcome5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblWellcome5.setText("Wellcome to Boutique sanaa");

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hijab" }));

        bnlimage3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblimage4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblimage4.setText("Image");

        javax.swing.GroupLayout bnlimage3Layout = new javax.swing.GroupLayout(bnlimage3);
        bnlimage3.setLayout(bnlimage3Layout);
        bnlimage3Layout.setHorizontalGroup(
            bnlimage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnlimage3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblimage4)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        bnlimage3Layout.setVerticalGroup(
            bnlimage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnlimage3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblimage4)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        bnlimage4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblimage5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblimage5.setText("Image");

        javax.swing.GroupLayout bnlimage4Layout = new javax.swing.GroupLayout(bnlimage4);
        bnlimage4.setLayout(bnlimage4Layout);
        bnlimage4Layout.setHorizontalGroup(
            bnlimage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnlimage4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblimage5)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        bnlimage4Layout.setVerticalGroup(
            bnlimage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnlimage4Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblimage5)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        lblimage6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Image");

        javax.swing.GroupLayout lblimage6Layout = new javax.swing.GroupLayout(lblimage6);
        lblimage6.setLayout(lblimage6Layout);
        lblimage6Layout.setHorizontalGroup(
            lblimage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblimage6Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        lblimage6Layout.setVerticalGroup(
            lblimage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblimage6Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel4)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        lblprice4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblprice4.setText("9JD");

        lblprice5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblprice5.setText("6JD");

        lblprice6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblprice6.setText("5JD");

        btnback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblprice4)
                .addGap(157, 157, 157)
                .addComponent(lblprice5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblprice6)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblWellcome5)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(bnlimage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bnlimage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblimage6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblWellcome5)
                        .addGap(40, 40, 40)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(bnlimage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(bnlimage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(lblimage6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblprice4)
                    .addComponent(lblprice5)
                    .addComponent(lblprice6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnback)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
 
    new minpage().setVisible(true);
    this.dispose();

    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hijabpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hijabpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hijabpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hijabpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hijabpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bnlimage3;
    private javax.swing.JPanel bnlimage4;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblWellcome5;
    private javax.swing.JLabel lblimage4;
    private javax.swing.JLabel lblimage5;
    private javax.swing.JPanel lblimage6;
    private javax.swing.JLabel lblprice4;
    private javax.swing.JLabel lblprice5;
    private javax.swing.JLabel lblprice6;
    // End of variables declaration//GEN-END:variables
}
