/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class minpage extends javax.swing.JFrame {
    /**
     * Creates new form minpage
     */
    public minpage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("windows")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblwellcome2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnAddtocart = new javax.swing.JButton();
        pnlimage = new javax.swing.JPanel();
        lblimage1 = new javax.swing.JLabel();
        pnlimage2 = new javax.swing.JPanel();
        lblimage3 = new javax.swing.JLabel();
        lblprice1 = new javax.swing.JLabel();
        lblprice2 = new javax.swing.JLabel();
        lblprice3 = new javax.swing.JLabel();
        pnlimage1 = new javax.swing.JPanel();
        lblimage2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblwellcome2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblwellcome2.setText("Wellcome to Boutique sanaa");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abayas ", "Hijabs", "Niqab" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSearch.setText("Search");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnAddtocart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddtocart.setText("Add to cart");
        btnAddtocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtocartActionPerformed(evt);
            }
        });

        pnlimage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblimage1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblimage1.setText("Image");

        javax.swing.GroupLayout pnlimageLayout = new javax.swing.GroupLayout(pnlimage);
        pnlimage.setLayout(pnlimageLayout);
        pnlimageLayout.setHorizontalGroup(
            pnlimageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlimageLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblimage1)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlimageLayout.setVerticalGroup(
            pnlimageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlimageLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblimage1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlimage2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblimage3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblimage3.setText("Image");

        javax.swing.GroupLayout pnlimage2Layout = new javax.swing.GroupLayout(pnlimage2);
        pnlimage2.setLayout(pnlimage2Layout);
        pnlimage2Layout.setHorizontalGroup(
            pnlimage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlimage2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblimage3)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnlimage2Layout.setVerticalGroup(
            pnlimage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlimage2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblimage3)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        lblprice1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblprice1.setText("50JD");

        lblprice2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblprice2.setText("65JD");

        lblprice3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblprice3.setText("40JD");

        pnlimage1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblimage2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblimage2.setText("Image");

        javax.swing.GroupLayout pnlimage1Layout = new javax.swing.GroupLayout(pnlimage1);
        pnlimage1.setLayout(pnlimage1Layout);
        pnlimage1Layout.setHorizontalGroup(
            pnlimage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlimage1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblimage2)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlimage1Layout.setVerticalGroup(
            pnlimage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlimage1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblimage2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblwellcome2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnAddtocart, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(48, 48, 48)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(pnlimage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlimage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlimage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblprice1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(lblprice2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(lblprice3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblwellcome2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlimage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlimage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprice1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprice2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprice3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnAddtocart)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    String selected = jComboBox1.getSelectedItem().toString();

if(selected.equals("Hijabs"))
{
    new Hijabpage().setVisible(true);
    this.dispose();
}
else if(selected.equals("Niqab"))
{
    new Niqabpage().setVisible(true);
    this.dispose();
}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
       String search = txtSearch.getText();

    if(search.equalsIgnoreCase("Hijab"))
    {
    new Hijabpage().setVisible(true);
    this.dispose();
    }
  else if(search.equalsIgnoreCase("Niqab"))
{
    new Niqabpage().setVisible(true);
    this.dispose();
}
    else
{
    javax.swing.JOptionPane.showMessageDialog(this,
            "Product not found");
}
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnAddtocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtocartActionPerformed
 

    String search = txtSearch.getText().trim();

    if (!search.isEmpty() && !search.equalsIgnoreCase("Search")) {

        javax.swing.JOptionPane.showMessageDialog(this,
                search + " added to cart successfully");

    } else {

        javax.swing.JOptionPane.showMessageDialog(this,
                "Item added to cart successfully");
    }

    new page().setVisible(true);

    this.dispose();

      
    }//GEN-LAST:event_btnAddtocartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new minpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtocart;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblimage1;
    private javax.swing.JLabel lblimage2;
    private javax.swing.JLabel lblimage3;
    private javax.swing.JLabel lblprice1;
    private javax.swing.JLabel lblprice2;
    private javax.swing.JLabel lblprice3;
    private javax.swing.JLabel lblwellcome2;
    private javax.swing.JPanel pnlimage;
    private javax.swing.JPanel pnlimage1;
    private javax.swing.JPanel pnlimage2;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
