/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Niqabpage extends javax.swing.JFrame {

    /**
     * Creates new form Niqabpage
     */
    public Niqabpage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("windows")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWellcome6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        bnlimage6 = new javax.swing.JPanel();
        lblimage7 = new javax.swing.JLabel();
        bnlimage7 = new javax.swing.JPanel();
        lblimage8 = new javax.swing.JLabel();
        lblprice7 = new javax.swing.JLabel();
        lblprice8 = new javax.swing.JLabel();
        lblprice9 = new javax.swing.JLabel();
        bnlimage8 = new javax.swing.JPanel();
        lblimage9 = new javax.swing.JLabel();
        btnback1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWellcome6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblWellcome6.setText("Wellcome to Boutique sanaa");

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niqab" }));

        bnlimage6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblimage7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblimage7.setText("Image");

        javax.swing.GroupLayout bnlimage6Layout = new javax.swing.GroupLayout(bnlimage6);
        bnlimage6.setLayout(bnlimage6Layout);
        bnlimage6Layout.setHorizontalGroup(
            bnlimage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnlimage6Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblimage7)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        bnlimage6Layout.setVerticalGroup(
            bnlimage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnlimage6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblimage7)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        bnlimage7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblimage8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblimage8.setText("Image");

        javax.swing.GroupLayout bnlimage7Layout = new javax.swing.GroupLayout(bnlimage7);
        bnlimage7.setLayout(bnlimage7Layout);
        bnlimage7Layout.setHorizontalGroup(
            bnlimage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnlimage7Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblimage8)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        bnlimage7Layout.setVerticalGroup(
            bnlimage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnlimage7Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblimage8)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        lblprice7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblprice7.setText("30JD");

        lblprice8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblprice8.setText("45JD");

        lblprice9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblprice9.setText("50JD");

        bnlimage8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblimage9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblimage9.setText("Image");

        javax.swing.GroupLayout bnlimage8Layout = new javax.swing.GroupLayout(bnlimage8);
        bnlimage8.setLayout(bnlimage8Layout);
        bnlimage8Layout.setHorizontalGroup(
            bnlimage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnlimage8Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblimage9)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        bnlimage8Layout.setVerticalGroup(
            bnlimage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bnlimage8Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblimage9)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        btnback1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnback1.setText("Back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWellcome6, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bnlimage6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bnlimage7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bnlimage8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblprice7)
                        .addGap(167, 167, 167)
                        .addComponent(lblprice8)
                        .addGap(103, 103, 103)
                        .addComponent(lblprice9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnback1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblWellcome6)
                .addGap(38, 38, 38)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnlimage6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnlimage7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnlimage8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprice7)
                    .addComponent(lblprice8)
                    .addComponent(lblprice9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnback1)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed

    new minpage().setVisible(true);
    this.dispose();

    }//GEN-LAST:event_btnback1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Niqabpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Niqabpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Niqabpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Niqabpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Niqabpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bnlimage6;
    private javax.swing.JPanel bnlimage7;
    private javax.swing.JPanel bnlimage8;
    private javax.swing.JButton btnback1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblWellcome6;
    private javax.swing.JLabel lblimage7;
    private javax.swing.JLabel lblimage8;
    private javax.swing.JLabel lblimage9;
    private javax.swing.JLabel lblprice7;
    private javax.swing.JLabel lblprice8;
    private javax.swing.JLabel lblprice9;
    // End of variables declaration//GEN-END:variables
}
